name: glados
version: 0.1.0.0
dependencies:
  - base >= 4.7 && < 5
  - mtl
  - process
  - directory
library:
  source-dirs: src
  exposed-modules:
    - Parser
    - Evaluator
    - Parser.LISP
  ghc-options:
    - -fhpc
  dependencies:
    - mtl
executables:
  glados:
    main: Main.hs
    source-dirs: src

tests:
  glados-test:
    main: Test.hs
    source-dirs: test
    other-modules:
      - TestHelper
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -fhpc
    dependencies:
      - glados
      - tasty
      - tasty-hspec
      - hspec
      - process
      - filepath
      - directory