name: glados
version: 0.1.0.0
dependencies:
  - base >= 4.7 && < 5
  - mtl
  - process
  - directory
library:
  source-dirs: src
  exposed-modules:
    - Parser
    - Evaluator
    - Parser.LISP
  ghc-options:
    - -fhpc
  dependencies:
    - mtl
executables:
  glados:
    main: Main.hs
    source-dirs: src

tests:
  glados-test:
    main: Test.hs
    source-dirs: test
    other-modules:
      - LispCases.AdvancedLambda.AdvancedLambda
      - LispCases.ArithmeticOps.ArithmeticOps
      - LispCases.BooleanOps.BooleanOps
      - LispCases.Builtins.Builtins
      - LispCases.Call.Call
      - LispCases.Comparisons.Comparisons
      - LispCases.DataStructures.DataStructures
      - LispCases.DefineAndRecursion.DefineAndRecursion
      - LispCases.EdgeCases.EdgeCases
      - LispCases.Error.Error
      - LispCases.Factorial.Factorial
      - LispCases.Foo.Foo
      - LispCases.Function.Function
      - LispCases.If.If
      - LispCases.Lambda.Lambda
      - LispCases.ParseErrors.ParseErrors
      - LispCases.RuntimeErrors.RuntimeErrors
      - LispCases.SpecialCases.SpecialCases
      - LispCases.Superior.Superior
      - LispCases.SymbolHandling.SymbolHandling
      - LispCases.UnboundVariables.UnboundVariables
      - ParserCombinators.ParserCombinators
      - TestHelper
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -fhpc
    dependencies:
      - glados
      - tasty
      - tasty-hspec
      - hspec
      - process
      - filepath
      - directory