{-# LANGUAGE OverloadedStrings #-}
module Compiler.TopLevel where

import AST
import qualified Parser as P
import Compiler.Types
import Compiler.Boxing
import Compiler.Expr
import Compiler.Codegen
import Control.Monad (forM, forM_, foldM)
import Control.Monad.State
import Data.List (intercalate)
import qualified Data.Map as M

compileTopLevel :: TopLevel -> Compiler ()
compileTopLevel (TLImport _ _) = return ()

compileTopLevel (TLFn name params body) = do
  modify $ \s -> s { csFuncNames = name : csFuncNames s }
  
  oldCode <- gets csCode
  oldLocals <- gets csLocals
  oldFunctions <- gets csFunctions
  modify $ \s -> s { csCode = [], csLocals = M.empty, csFunctions = [] }
  
  forM_ params $ \p -> setLocal p ("%" ++ p ++ ".ptr")
  
  let body' = P.desugarPipes body
  result <- compileExpr body'
  emit $ "  ret %Value " ++ result
  
  bodyCode <- gets csCode
  nestedFuncs <- gets csFunctions
  
  let paramList = intercalate ", " ["%Value* %" ++ p ++ ".ptr" | p <- params]
      funcDef = ["define %Value @" ++ name ++ "(" ++ paramList ++ ") {",
                 "entry:"] ++ bodyCode ++ ["}", ""]
  
  modify $ \s -> s { csCode = oldCode, 
                     csLocals = oldLocals, 
                     csFunctions = oldFunctions ++ nestedFuncs ++ funcDef }

compileTopLevel (TLProc name params stmts) = do
  modify $ \s -> s { csFuncNames = name : csFuncNames s }
  
  oldCode <- gets csCode
  oldLocals <- gets csLocals
  oldFunctions <- gets csFunctions
  modify $ \s -> s { csCode = [], csLocals = M.empty, csFunctions = [] }
  
  forM_ params $ \p -> setLocal p ("%" ++ p ++ ".ptr")
  
  forM_ stmts compileTopLevel
  
  result <- boxInt "0"
  emit $ "  ret %Value " ++ result
  
  bodyCode <- gets csCode
  nestedFuncs <- gets csFunctions
  
  let paramList = intercalate ", " ["%Value* %" ++ p ++ ".ptr" | p <- params]
      funcDef = ["define %Value @" ++ name ++ "(" ++ paramList ++ ") {",
                 "entry:"] ++ bodyCode ++ ["}", ""]
  
  modify $ \s -> s { csCode = oldCode, 
                     csLocals = oldLocals, 
                     csFunctions = oldFunctions ++ nestedFuncs ++ funcDef }

compileTopLevel (TLLet name expr) = do
  let expr' = P.desugarPipes expr
  val <- compileExpr expr'
  ptr <- freshReg
  emit $ "  " ++ ptr ++ " = alloca %Value"
  emit $ "  store %Value " ++ val ++ ", %Value* " ++ ptr
  setLocal name ptr

compileTopLevel (TLExpr expr) = do
  let expr' = P.desugarPipes expr
  _ <- compileExpr expr'
  return ()

compileProgram :: Program -> String
compileProgram prog = evalState action initialState
  where
    action = do
      genPrelude
      
      -- Single pass: collect function names and compile them
      forM_ prog $ \tl -> case tl of
        TLFn name _ _ -> do
          modify $ \s -> s { csFuncNames = name : csFuncNames s }
          compileTopLevel tl
        TLProc name _ _ -> do
          modify $ \s -> s { csFuncNames = name : csFuncNames s }
          compileTopLevel tl
        _ -> return ()
      
      emit "define i32 @main() {"
      emit "entry:"
      
      lastVal <- foldM compileMain Nothing prog
      
      case lastVal of
        Just reg -> do
          tag <- getTag reg
          raw <- unboxValue reg
          isInt <- freshReg
          emit $ "  " ++ isInt ++ " = icmp eq i64 " ++ tag ++ ", 0"
          
          retInt <- freshLabel "ret.int"
          retZero <- freshLabel "ret.zero"
          
          emit $ "  br i1 " ++ isInt ++ ", label %" ++ retInt ++
            ", label %" ++ retZero
          
          emit $ retInt ++ ":"
          truncated <- freshReg
          emit $ "  " ++ truncated ++ " = trunc i64 " ++ raw ++ " to i32"
          emit $ "  ret i32 " ++ truncated
          
          emit $ retZero ++ ":"
          emit "  ret i32 0"
        Nothing -> emit "  ret i32 0"
      
      emit "}"
      
      funcs <- gets csFunctions
      strs <- gets csStrings
      mainCode <- gets csCode
      
      return $ unlines $
        ["; Generated by Flux compiler", ""] ++
        genStrings strs ++
        [""] ++
        funcs ++
        mainCode
    
    compileMain mLast tl = case tl of
      TLImport {} -> return mLast
      TLFn {} -> return mLast
      TLProc {} -> return mLast
      TLLet name expr ->
        compileTopLevel (TLLet name expr) >> return mLast
      TLExpr expr -> do
        let expr' = P.desugarPipes expr
        result <- compileExpr expr'
        return (Just result)

compileProgramToFile :: Program -> FilePath -> IO ()
compileProgramToFile prog path =
  let ir = compileProgram prog
  in writeFile path ir
