; Generated by Flux compiler

@.str.0 = private unnamed_addr constant [5 x i8] c"%ld\0A\00"
@.str.1 = private unnamed_addr constant [4 x i8] c"#t\0A\00"
@.str.2 = private unnamed_addr constant [4 x i8] c"#f\0A\00"
@.str.3 = private unnamed_addr constant [3 x i8] c"%s\00"
@.str.4 = private unnamed_addr constant [5 x i8] c"%ld\0A\00"
@.str.5 = private unnamed_addr constant [4 x i8] c"#t\0A\00"
@.str.6 = private unnamed_addr constant [4 x i8] c"#f\0A\00"
@.str.7 = private unnamed_addr constant [3 x i8] c"%s\00"
@.str.8 = private unnamed_addr constant [5 x i8] c"%ld\0A\00"
@.str.9 = private unnamed_addr constant [4 x i8] c"#t\0A\00"
@.str.10 = private unnamed_addr constant [4 x i8] c"#f\0A\00"
@.str.11 = private unnamed_addr constant [3 x i8] c"%s\00"

; Runtime declarations
declare i32 @printf(i8*, ...)
declare i8* @malloc(i64)
declare void @free(i8*)
declare i8* @strcpy(i8*, i8*)
declare i64 @strlen(i8*)

; Boxed value type: { i64 tag, i64 data }
%Value = type { i64, i64 }

; Closure type: { i8* funcptr, i64 env_size, %Value* env }
%Closure = type { i8*, i64, %Value* }

; Array type for lists/tuples: { i64 size, %Value* elements }
%Array = type { i64, %Value* }

define %Value @makeAdder(%Value* %x.ptr) {
entry:
define %Value @lambda0(%Value* %env.ptr, %Value* %y.ptr) {
entry:
  %r0 = getelementptr %Value, %Value* %env.ptr, i64 0
  %r1 = load %Value, %Value* %r0
  %r2 = load %Value, %Value* %y.ptr
  %r3 = extractvalue %Value %r1, 1
  %r4 = extractvalue %Value %r2, 1
  %r5 = add i64 %r3, %r4
  %r6 = insertvalue %Value { i64 0, i64 undef }, i64 %r5, 1
  ret %Value %r6
}

  %r9 = call i8* @malloc(i64 24)
  %r10 = bitcast i8* %r9 to %Closure*
  %r11 = getelementptr %Closure, %Closure* %r10, i32 0, i32 0
  %r12 = bitcast %Value (%Value*, %Value*)* @lambda0 to i8*
  store i8* %r12, i8** %r11
  %r13 = getelementptr %Closure, %Closure* %r10, i32 0, i32 1
  store i64 1, i64* %r13
  %r14 = call i8* @malloc(i64 16)
  %r15 = bitcast i8* %r14 to %Value*
  %r16 = getelementptr %Closure, %Closure* %r10, i32 0, i32 2
  store %Value* %r15, %Value** %r16
  %r17 = load %Value, %Value* %x.ptr
  %r18 = getelementptr %Value, %Value* %r15, i64 0
  store %Value %r17, %Value* %r18
  %r19 = ptrtoint i8* %r9 to i64
  %r20 = insertvalue %Value { i64 5, i64 undef }, i64 %r19, 1
  ret %Value %r20
}

define i32 @main() {
entry:
  %r21 = insertvalue %Value { i64 0, i64 undef }, i64 5, 1
  %r24 = alloca %Value
  store %Value %r21, %Value* %r24
  %r25 = call %Value @makeAdder(%Value* %r24)
  %r26 = alloca %Value
  store %Value %r25, %Value* %r26
  %r27 = insertvalue %Value { i64 0, i64 undef }, i64 10, 1
  %r30 = alloca %Value
  store %Value %r27, %Value* %r30
  %r31 = call %Value @makeAdder(%Value* %r30)
  %r32 = alloca %Value
  store %Value %r31, %Value* %r32
  %r33 = load %Value, %Value* %r26
  %r34 = extractvalue %Value %r33, 1
  %r35 = inttoptr i64 %r34 to %Closure*
  %r36 = getelementptr %Closure, %Closure* %r35, i32 0, i32 0
  %r37 = load i8*, i8** %r36
  %r38 = getelementptr %Closure, %Closure* %r35, i32 0, i32 1
  %r39 = load i64, i64* %r38
  %r40 = getelementptr %Closure, %Closure* %r35, i32 0, i32 2
  %r41 = load %Value*, %Value** %r40
  %r42 = icmp ne i64 %r39, 0
  br i1 %r42, label %call.withenv1, label %call.noenv2
call.withenv1:
  %r43 = insertvalue %Value { i64 0, i64 undef }, i64 3, 1
  %r46 = alloca %Value
  store %Value %r43, %Value* %r46
  %r47 = bitcast i8* %r37 to %Value (%Value*, %Value*)*
  %r48 = call %Value %r47(%Value* %r41, %Value* %r46)
  br label %call.end3
call.noenv2:
  %r49 = insertvalue %Value { i64 0, i64 undef }, i64 3, 1
  %r52 = alloca %Value
  store %Value %r49, %Value* %r52
  %r53 = bitcast i8* %r37 to %Value (%Value*)*
  %r54 = call %Value %r53(%Value* %r52)
  br label %call.end3
call.end3:
  %r55 = phi %Value [ %r48, %call.withenv1 ], [ %r54, %call.noenv2 ]
  %r56 = extractvalue %Value %r55, 0
  %r57 = extractvalue %Value %r55, 1
  %r58 = icmp eq i64 %r56, 0
  br i1 %r58, label %print.int4, label %print.notint8
print.int4:
  %r61 = getelementptr [6 x i8], [6 x i8]* @.str.0, i64 0, i64 0
  call i32 (i8*, ...) @printf(i8* %r61, i64 %r57)
  br label %print.end7
print.notint8:
  %r59 = icmp eq i64 %r56, 1
  br i1 %r59, label %print.bool5, label %print.str6
print.bool5:
  %r62 = icmp ne i64 %r57, 0
  %r63 = getelementptr [4 x i8], [4 x i8]* @.str.1, i64 0, i64 0
  %r64 = getelementptr [4 x i8], [4 x i8]* @.str.2, i64 0, i64 0
  %r65 = select i1 %r62, i8* %r63, i8* %r64
  call i32 (i8*, ...) @printf(i8* %r65)
  br label %print.end7
print.str6:
  %r66 = inttoptr i64 %r57 to i8*
  %r67 = getelementptr [3 x i8], [3 x i8]* @.str.3, i64 0, i64 0
  call i32 (i8*, ...) @printf(i8* %r67, i8* %r66)
  br label %print.end7
print.end7:
  %r68 = load %Value, %Value* %r32
  %r69 = extractvalue %Value %r68, 1
  %r70 = inttoptr i64 %r69 to %Closure*
  %r71 = getelementptr %Closure, %Closure* %r70, i32 0, i32 0
  %r72 = load i8*, i8** %r71
  %r73 = getelementptr %Closure, %Closure* %r70, i32 0, i32 1
  %r74 = load i64, i64* %r73
  %r75 = getelementptr %Closure, %Closure* %r70, i32 0, i32 2
  %r76 = load %Value*, %Value** %r75
  %r77 = icmp ne i64 %r74, 0
  br i1 %r77, label %call.withenv9, label %call.noenv10
call.withenv9:
  %r78 = insertvalue %Value { i64 0, i64 undef }, i64 3, 1
  %r81 = alloca %Value
  store %Value %r78, %Value* %r81
  %r82 = bitcast i8* %r72 to %Value (%Value*, %Value*)*
  %r83 = call %Value %r82(%Value* %r76, %Value* %r81)
  br label %call.end11
call.noenv10:
  %r84 = insertvalue %Value { i64 0, i64 undef }, i64 3, 1
  %r87 = alloca %Value
  store %Value %r84, %Value* %r87
  %r88 = bitcast i8* %r72 to %Value (%Value*)*
  %r89 = call %Value %r88(%Value* %r87)
  br label %call.end11
call.end11:
  %r90 = phi %Value [ %r83, %call.withenv9 ], [ %r89, %call.noenv10 ]
  %r91 = extractvalue %Value %r90, 0
  %r92 = extractvalue %Value %r90, 1
  %r93 = icmp eq i64 %r91, 0
  br i1 %r93, label %print.int12, label %print.notint16
print.int12:
  %r96 = getelementptr [6 x i8], [6 x i8]* @.str.4, i64 0, i64 0
  call i32 (i8*, ...) @printf(i8* %r96, i64 %r92)
  br label %print.end15
print.notint16:
  %r94 = icmp eq i64 %r91, 1
  br i1 %r94, label %print.bool13, label %print.str14
print.bool13:
  %r97 = icmp ne i64 %r92, 0
  %r98 = getelementptr [4 x i8], [4 x i8]* @.str.5, i64 0, i64 0
  %r99 = getelementptr [4 x i8], [4 x i8]* @.str.6, i64 0, i64 0
  %r100 = select i1 %r97, i8* %r98, i8* %r99
  call i32 (i8*, ...) @printf(i8* %r100)
  br label %print.end15
print.str14:
  %r101 = inttoptr i64 %r92 to i8*
  %r102 = getelementptr [3 x i8], [3 x i8]* @.str.7, i64 0, i64 0
  call i32 (i8*, ...) @printf(i8* %r102, i8* %r101)
  br label %print.end15
print.end15:
  %r103 = load %Value, %Value* %r26
  %r104 = extractvalue %Value %r103, 1
  %r105 = inttoptr i64 %r104 to %Closure*
  %r106 = getelementptr %Closure, %Closure* %r105, i32 0, i32 0
  %r107 = load i8*, i8** %r106
  %r108 = getelementptr %Closure, %Closure* %r105, i32 0, i32 1
  %r109 = load i64, i64* %r108
  %r110 = getelementptr %Closure, %Closure* %r105, i32 0, i32 2
  %r111 = load %Value*, %Value** %r110
  %r112 = icmp ne i64 %r109, 0
  br i1 %r112, label %call.withenv17, label %call.noenv18
call.withenv17:
  %r113 = insertvalue %Value { i64 0, i64 undef }, i64 7, 1
  %r116 = alloca %Value
  store %Value %r113, %Value* %r116
  %r117 = bitcast i8* %r107 to %Value (%Value*, %Value*)*
  %r118 = call %Value %r117(%Value* %r111, %Value* %r116)
  br label %call.end19
call.noenv18:
  %r119 = insertvalue %Value { i64 0, i64 undef }, i64 7, 1
  %r122 = alloca %Value
  store %Value %r119, %Value* %r122
  %r123 = bitcast i8* %r107 to %Value (%Value*)*
  %r124 = call %Value %r123(%Value* %r122)
  br label %call.end19
call.end19:
  %r125 = phi %Value [ %r118, %call.withenv17 ], [ %r124, %call.noenv18 ]
  %r126 = extractvalue %Value %r125, 0
  %r127 = extractvalue %Value %r125, 1
  %r128 = icmp eq i64 %r126, 0
  br i1 %r128, label %print.int20, label %print.notint24
print.int20:
  %r131 = getelementptr [6 x i8], [6 x i8]* @.str.8, i64 0, i64 0
  call i32 (i8*, ...) @printf(i8* %r131, i64 %r127)
  br label %print.end23
print.notint24:
  %r129 = icmp eq i64 %r126, 1
  br i1 %r129, label %print.bool21, label %print.str22
print.bool21:
  %r132 = icmp ne i64 %r127, 0
  %r133 = getelementptr [4 x i8], [4 x i8]* @.str.9, i64 0, i64 0
  %r134 = getelementptr [4 x i8], [4 x i8]* @.str.10, i64 0, i64 0
  %r135 = select i1 %r132, i8* %r133, i8* %r134
  call i32 (i8*, ...) @printf(i8* %r135)
  br label %print.end23
print.str22:
  %r136 = inttoptr i64 %r127 to i8*
  %r137 = getelementptr [3 x i8], [3 x i8]* @.str.11, i64 0, i64 0
  call i32 (i8*, ...) @printf(i8* %r137, i8* %r136)
  br label %print.end23
print.end23:
  %r138 = extractvalue %Value %r125, 0
  %r139 = extractvalue %Value %r125, 1
  %r140 = icmp eq i64 %r138, 0
  br i1 %r140, label %ret.int25, label %ret.zero26
ret.int25:
  %r141 = trunc i64 %r139 to i32
  ret i32 %r141
ret.zero26:
  ret i32 0
}
