name: flux
version: 0.1.0.0
dependencies:
  - base >= 4.7 && < 5
  - megaparsec
  - text
  - parser-combinators
  - containers

executables:
  flux:
    main: Main.hs
    source-dirs: src
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
